const { SESClient, SendEmailCommand } = require('@aws-sdk/client-ses');
const { S3Client, GetObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');

const ses = new SESClient({});
const s3 = new S3Client({});

const MAIL_FROM = process.env.MAIL_FROM;
const MAIL_TO = process.env.MAIL_TO;
const PRESIGNED_URL_EXPIRES_SECONDS = Number(
  process.env.PRESIGNED_URL_EXPIRES_SECONDS || '86400',
);

function getStringValue(attribute) {
  return attribute?.S || '';
}

function getNumberValue(attribute) {
  return attribute?.N ? Number(attribute.N) : null;
}

function formatConfidence(confidence) {
  if (confidence === null || confidence === undefined) return '-';
  return `${confidence.toFixed(2)}%`;
}

function buildHtmlBody({
  cameraId,
  detectedAt,
  label,
  confidence,
  kumaCount,
  bboxStatus,
  imageUrl,
  s3Key,
}) {
  return `
  <div style="font-family: Arial, sans-serif; background-color: #f6f8fa; padding: 24px;">
    <div style="max-width: 760px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; border: 1px solid #e5e7eb;">
      
      <div style="background-color: #1f2937; color: #ffffff; padding: 20px 24px;">
        <h1 style="margin: 0; font-size: 22px;">Kuma Detection Alert</h1>
        <p style="margin: 8px 0 0; color: #d1d5db;">監視カメラ映像からクマを検出しました</p>
      </div>

      <div style="padding: 24px;">
        <div style="background-color: #fff7ed; border-left: 5px solid #f97316; padding: 14px 16px; margin-bottom: 24px;">
          <strong>検出結果:</strong> ${label} を ${formatConfidence(confidence)} の信頼度で検出しました。ʕ•ᴥ•ʔ
        </div>

        <h2 style="font-size: 18px; margin-bottom: 12px;">検出画像</h2>
        ${
          imageUrl
            ? `<img src="${imageUrl}" width="700" alt="Kuma Detection Image" style="max-width: 100%; border: 1px solid #d1d5db; border-radius: 8px;" />`
            : `<p>Bounding Box付き画像はありません。</p>`
        }

        <h2 style="font-size: 18px; margin: 28px 0 12px;">検出情報</h2>
        <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
          <tr>
            <th style="text-align:left; padding:10px; background:#f3f4f6; border:1px solid #e5e7eb;">項目</th>
            <th style="text-align:left; padding:10px; background:#f3f4f6; border:1px solid #e5e7eb;">値</th>
          </tr>
          <tr><td style="padding:10px; border:1px solid #e5e7eb;">Camera ID</td><td style="padding:10px; border:1px solid #e5e7eb;">${cameraId}</td></tr>
          <tr><td style="padding:10px; border:1px solid #e5e7eb;">Detected At</td><td style="padding:10px; border:1px solid #e5e7eb;">${detectedAt}</td></tr>
          <tr><td style="padding:10px; border:1px solid #e5e7eb;">Label</td><td style="padding:10px; border:1px solid #e5e7eb;">${label}</td></tr>
          <tr><td style="padding:10px; border:1px solid #e5e7eb;">Confidence</td><td style="padding:10px; border:1px solid #e5e7eb;">${formatConfidence(confidence)}</td></tr>
          <tr><td style="padding:10px; border:1px solid #e5e7eb;">Kuma Count</td><td style="padding:10px; border:1px solid #e5e7eb;">${kumaCount}</td></tr>
          <tr><td style="padding:10px; border:1px solid #e5e7eb;">Bounding Box</td><td style="padding:10px; border:1px solid #e5e7eb;">${bboxStatus}</td></tr>
        </table>

        <h2 style="font-size: 18px; margin: 28px 0 12px;">保存先</h2>
        <p style="font-size: 13px; background:#f9fafb; padding:12px; border-radius:8px; word-break:break-all;">
          ${s3Key || '-'}
        </p>

        <p style="font-size: 12px; color: #6b7280; margin-top: 28px;">
          This alert was generated by AWS serverless architecture: Kinesis Video Streams → Lambda → Amazon Rekognition → S3 → DynamoDB → Email.
        </p>
      </div>
    </div>
  </div>
  `;
}

exports.handler = async (event) => {
  console.log('Notifier invoked:', JSON.stringify(event));

  for (const record of event.Records || []) {
    if (record.eventName !== 'INSERT') {
      continue;
    }

    const image = record.dynamodb?.NewImage;
    if (!image) {
      continue;
    }

    const cameraId = getStringValue(image.cameraId);
    const detectedAt = getStringValue(image.detectedAt);
    const label = getStringValue(image.rawLabelName) || 'Bear';
    const confidence = getNumberValue(image.confidence);
    const kumaCount = getNumberValue(image.kumaCount) || 1;

    const s3Bucket = getStringValue(image.s3Bucket);
    const s3Key = getStringValue(image.s3Key);
    const s3KeyBbox = getStringValue(image.s3KeyBbox);

    const bboxStatus = s3KeyBbox ? 'あり' : 'なし';

    let imageUrl = null;
    if (s3Bucket && s3KeyBbox) {
      imageUrl = await getSignedUrl(
        s3,
        new GetObjectCommand({
          Bucket: s3Bucket,
          Key: s3KeyBbox,
        }),
        { expiresIn: PRESIGNED_URL_EXPIRES_SECONDS },
      );
    }

    const htmlBody = buildHtmlBody({
      cameraId,
      detectedAt,
      label,
      confidence,
      kumaCount,
      bboxStatus,
      imageUrl,
      s3Key: s3KeyBbox || s3Key,
    });

    const textBody = [
      'Kuma Detection Alert',
      '',
      `Camera ID: ${cameraId}`,
      `Detected At: ${detectedAt}`,
      `Label: ${label}`,
      `Confidence: ${formatConfidence(confidence)}`,
      `Kuma Count: ${kumaCount}`,
      `S3 Key: ${s3KeyBbox || s3Key || '-'}`,
    ].join('\n');

    await ses.send(
      new SendEmailCommand({
        Source: MAIL_FROM,
        Destination: {
          ToAddresses: [MAIL_TO],
        },
        Message: {
          Subject: {
            Data: '【Kuma Detection Alert】クマを検出しました',
            Charset: 'UTF-8',
          },
          Body: {
            Text: {
              Data: textBody,
              Charset: 'UTF-8',
            },
            Html: {
              Data: htmlBody,
              Charset: 'UTF-8',
            },
          },
        },
      }),
    );

    console.log('SES mail sent:', {
      cameraId,
      detectedAt,
      confidence,
      s3Key,
      s3KeyBbox,
    });
  }

  return { statusCode: 200 };
};
